### ISSUE TITLE
Tests fall on non-x86_64 platforms

### ISSUE THREAD

**Issue by RiderALT** [aantron/luv#101]
x86_64 is hardcoded for uname check in test/misc.ml:
      Alcotest.(check string) "machine" "x86_64" uname.machine;

**Comment by aantron** [comment]
Thanks. In the [above commit](https://github.com/aantron/luv/commit/4b77072a7d797047abadd73bb0748db808c3f07a), I relaxed the `uname` test to just check that the strings are non-empty. That seems somewhat future-proof to people running the tests on more platforms.
