### ISSUE TITLE
FAIL test on armh: libuv time not positive

### ISSUE THREAD

**Issue by RiderALT** [aantron/luv#102]
ASSERT libuv time not positive
FAIL libuv time not positive

luv 0.5.7 with internal libuv and external libuv - the same result.

ALT Linux Sisyphus, armh 32bit.

**Comment by aantron** [comment]
Can you try with the linked commit, 03627cd3032dedba439049cbd6044d2e87903496?

**Comment by RiderALT** [comment]
https://github.com/aantron/luv/commit/03627cd3032dedba439049cbd6044d2e87903496 did not help. 

ASSERT libuv time negative
FAIL libuv time negative

I'll see what is happening there in detail later.
Thanks.

**Comment by aantron** [comment]
Can you try with 42c2c7bc10b261c32e67a3726f07dcda2ae8b628? It is likely due to the `uint64_t` being taken modulo 2^31 before the comparison in the test case, during the conversion to OCaml `int`.

**Comment by RiderALT** [comment]
Anton, thanks. With the https://github.com/aantron/luv/commit/42c2c7bc10b261c32e67a3726f07dcda2ae8b628 test passed.
