### ISSUE TITLE
`luv_unix` not buildable with esy (dependency issue)

### ISSUE THREAD

**Issue by zbaylin** [aantron/luv#110]
Hey @aantron -- just one more issue I found with `luv_unix` :)

**OS:** macOS 11 (Big Sur)

**esy version**: 0.6.10

**Problem**: If I put both `luv` and `luv_unix` in my `package.json` like so:
```json
  "dependencies": {
    ...
    "@opam/luv": "aantron/luv:luv.opam#decdaad",
    "@opam/luv_unix": "aantron/luv:luv_unix.opam#decdaad",
    ...
  }
```
building `luv_unix` fails with the following message:
```
    File "src/unix/luv_unix.ml", line 22, characters 9-50:
    22 |       if C.Functions.Os_fd.is_invalid_handle_value os_fd then
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error: Unbound value C.Functions.Os_fd.is_invalid_handle_value
    error: command failed: 'dune' 'build' '-p' 'luv_unix' '-j' '4' (exited with 1)
```

It seems to be because `luv_unix` is being built before `luv`, but I don't know how to enforce the order (i.e. make esy know that `luv_unix` depends on `luv` being built first)

**Comment by aantron** [comment]
The order should already be forced by this line:

https://github.com/aantron/luv/blob/decdaad7511855d012e31f22b35538ddd874c08d/luv_unix.opam#L18

have you positively confirmed that they are being built out of order?

I can't seem to eyeball this issue. To rule out inherent problems with luv_unix, are you able to build luv_unix in a development checkout of the Luv repo (i.e. outside esy)?

**Comment by zbaylin** [comment]
> I can't seem to eyeball this issue. To rule out inherent problems with luv_unix, are you able to build luv_unix in a development checkout of the Luv repo (i.e. outside esy)?

I am, that's actually how I discovered #108 :)

> have you positively confirmed that they are being built out of order?

As far as I can tell I have -- I deleted all builds of `luv` and `luv_unix`, and when I run `esy build`, I get
```
info esy build 0.6.10 (using package.json)
info building @opam/luv_unix@github:aantron/luv:luv_unix.opam#decdaad@d41d8cd9
```
which seems to indicate that `luv_unix` is being built before `luv`

This seems like it might be an esy problem rather than an `luv` or `opam` one, but I'm not 100% sure of that

**Comment by aantron** [comment]
> ```
> info esy build 0.6.10 (using package.json)
> info building @opam/luv_unix@github:aantron/luv:luv_unix.opam#decdaad@d41d8cd9
> ```

Is there build output for `@opam/luv`? If not, it may be because it is cached. In light of that, this paste alone doesn't explicitly show the order. What does it mean that you have deleted all builds? Have you also deleted `~/.esy`? If so, can you confirm and/or show the full build output, with the positions of `@opam/luv` and `@opam/luv_unix` included? AFAIK if you had actually deleted all cached builds, you would see much more than this after `info esy build`.

**Comment by zbaylin** [comment]
Ah you're right, it looks like I missed one of the cached builds. 

I figured out what it was -- `luv_unix` was requesting `luv` 0.5.7 from OPAM, which didn't have the function definition. If I move the packages to `resolutions`, it works, i.e.:
```
  "resolutions": {
    "@opam/luv": "aantron/luv:luv.opam#decdaad",
    "@opam/luv_unix": "aantron/luv:luv_unix.opam#decdaad"
  }
```

Sorry for the confusion!

**Comment by aantron** [comment]
That's inconvenient. I would have hoped esy would build a consistent set of packages. I'll have to note this for future instructions, thanks!
