### ISSUE TITLE
TCP.getsockname and getpeername not working as expected

### ISSUE THREAD

**Issue by djs55** [aantron/luv#111]
Hi,

First of all thanks for the very nice, well documented library!

So far it's working well for me except I can't get seem to get useful data from `Luv.TCP.getsockname` and `Luv.TCP.getpeername`. I may well be misunderstanding something in the API though.

I modified the TCP echo example adding some `getsockname` and `getpeername` calls: https://github.com/djs55/luv/commit/9134c54a7aae55b2be1c79f6199cfa72ccb2ccf5

If I run the program I see
```
dave@m1 luv % ./_build/default/example/tcp_echo_server.exe
getsockname server: to_string = None, port = None
```
Although `getsockname server` succeeds after the `bind`, I can't seem to get information from the resulting `Sockaddr.t` with `Luv.Sockaddr.to_string` and `Luv.Sockaddr.port`.

Connecting to the server with `nc localhost 7000` I then see:
```
getsockname server: to_string = None, port = None
getpeername client: to_string = None, port = None
^C
```
^ in the listen callback I can't get useful info out of either `getsockname` or `getpeername`.

My host is a macOS Big Sur Apple Silicon machine. I'm testing current decdaad7511855d012e31f22b35538ddd874c08d as well as 0.5.7. I haven't tried Luv.UDP so far.

Thanks!

**Comment by aantron** [comment]
Thanks for the issue.

I won't be able to look into this in the coming days. However, you should be able to narrow down exactly what is going on quite quickly, given that you already have a checkout of Luv. You can simply insert prints into the various parts of Luv code. The vendored C code is fully integrated into the OCaml build, so if you need to examine the C side, you can just insert `fprintf`, and your changes should be immediately picked up when you rebuild the example. The libuv code is quite well-organized, and you should be able to navigate it quickly with some help from `grep`.
