### ISSUE TITLE
luv_unix is missing from opam-repository

### ISSUE THREAD

**Issue by talex5** [aantron/luv#120]
Using e.g. `Luv.Unix.Os_fd.Fd.to_unix` seems to require the `luv_unix` package. This is in the 0.5.9 release archive, but isn't in opam-repository.

```
$ tar tf luv-0.5.9.tar.gz|grep opam
luv-0.5.9/luv.opam
luv-0.5.9/luv_unix.opam

$ opam search luv
# Packages matching: match(*luv*)
# Name # Installed # Synopsis
luv    --          Binding to libuv: cross-platform asynchronous I/O
```

**Comment by aantron** [comment]
@talex5 the `luv_unix` package is so far not ready for release, though it may be good enough for some usages. So this is deliberate.

I will, however, consider your use case to prioritize getting `luv_unix` into shape. What are you doing with it/experimenting with?

**Comment by talex5** [comment]
I'm trying to add a luv backend to [eio](https://github.com/ocaml-multicore/eio). At the moment, eio only works on Linux (and only recent versions, as it uses io-uring). I think luv might be a good default choice for other platforms.

**Comment by aantron** [comment]
That's neat!

Are you able to use a pinned luv_unix for now, or do you need a speedy release? Also, even if you are using a pinned version, and need a release later, please do prod me and I'll release immediately.

I'm just hoping to find time to get that module finished a bit more before I have to release it, but there is also nothing wrong with pushing out an initial version, if it's already doing what you need.

**Comment by talex5** [comment]
There's no hurry at all; I just thought it was a mistake that it was missing.

I was going to use it to implement e.g. the reuseaddr socket option, but maybe the fact that luv doesn't have it is a clue that it isn't really needed and I should remove it from the eio API too...

**Comment by aantron** [comment]
AFAIK reuseaddr is very needed by many applications. libuv uses the [`uv_tcp_open`](http://docs.libuv.org/en/v1.x/tcp.html?highlight=socket%20option#c.uv_tcp_open) function as an escape hatch to allow the user to create a socket with all the right options, and then use it with libuv. You probably already saw that. There is an example [here](https://github.com/libuv/libuv/blob/bd7fcf1bfc411c4a57141002f97a163d6a00a925/test/test-tcp-open.c#L68). So, unfortunately, setting reuseaddr in a portable way is something that libuv does not yet address.

There is a [`UV_UDP_REUSEADDR`](http://docs.libuv.org/en/v1.x/udp.html#c.uv_udp_flags), however, so they might add it on request, or merge a PR.

**Comment by aantron** [comment]
Herer is a discussion about the related `SO_REUSEPORT` in the libuv repo: https://github.com/libuv/libuv/issues/386#issuecomment-109613592

**Comment by talex5** [comment]
> AFAIK reuseaddr is very needed by many applications

Yes, but it looks like libuv turns it on by default for all tcp connections, so that's OK:

https://github.com/libuv/libuv/blob/47e0c5c575e92a25e0da10fc25b2732942c929f3/src/unix/tcp.c#L164

So the question is whether it's ever useful to turn it *off*...

Actually, since it turns it on in `bind` rather than `init`, I guess we can't override it anway.

**Comment by talex5** [comment]
Any chance of a release with this soon? It would be useful for various things, including Lwt integration.

**Comment by aantron** [comment]
Package `luv_unix` was [released](https://opam.ocaml.org/packages/luv_unix/luv_unix.0.5.0/) on 2 February 2022, so closing this issue.
