### ISSUE TITLE
Question on vendored libuv

### ISSUE THREAD

**Issue by andreypopp** [aantron/luv#13]
Is this necessary?

I've packages libuv to be built with esy and thus can model a dependency on it instead (luv in this case finds it via `pkg-config`).

**Comment by aantron** [comment]
No, one option is to eventually factor it out as its own package (also in opam), if there is demand for that.

**Comment by aantron** [comment]
It does, however, make for very easy version correspondence, i.e. luv doesn't have to support multiple libuv API versions. So, if there is no natural demand for libuv to be separated, it seems nice to vendor it.

**Comment by aantron** [comment]
To give a concrete example, a recent version of libuv added [`uv_err_name_r`](http://docs.libuv.org/en/v1.x/errors.html#c.uv_err_name_r), to avoid a memory leak in `uv_err_name`. In luv, I just upgraded the libuv version and silently switched the implementation of `Luv.Error.err_name` to use the new function. If libuv is a separate package, we have to either maintain version constraints, or add discovery code to luv. We can do either one, but is it worth it?

What is your motivation for separating libuv?

**Comment by andreypopp** [comment]
Yeah, all these arguments are compelling to have libub vendored!

> What is your motivation for separating libuv?

I just had an esy package for libuv before and **did want** to install luv from sources as a dependency while **didn't want** to perform network requests (to clone libuv repo) during build process.

**Comment by andreypopp** [comment]
Sorry for the noise here. What do you think the right way to ask that sort of questions?

**Comment by aantron** [comment]
> Sorry for the noise here. What do you think the right way to ask that sort of questions?

No problem, it's a valid question, and I think here is the right place.

> I just had an esy package for libuv before and **did want** to install luv from sources as a dependency while **didn't want** to perform network requests (to clone libuv repo) during build process.

It's my understanding that (extra) network requests shouldn't be necessary.

When installing from source, there will already be a network request to clone luv. The clone should be recursive, so it will submit additional requests to clone libuv and gyp, but this is a normal part of the `git clone` process.

When installing from an archive, the archive will include a cloned libuv and gyp, so there should be no network requests beyond downloading the archive including everything.

Did you observe additional network requests? I definitely don't want that, either.

I'm not fully aware of the details of the libuv or gyp builds. Perhaps they do network requests of their own, but I would not expect that.

**Comment by aantron** [comment]
Also, I am (and will remain) open to factoring libuv out, I just want to be mindful of the tradeoffs :) If someone (including you :)) has a request for a separate libuv with a specific use in mind, I think we should help that :)

**Comment by andreypopp** [comment]
I think the problem was lying in esy workflow — I cloned luv repo and what I was expecting to do is just to do a `link:/path/to/luv/checkout` and that's it. Instead I had to go to the checkout and init submodules.

Ok, it's not a big problem (at least for now), I agree it's better not to overcomplicate the packaging. Maybe something should be fixed on esy side instead.

**Comment by aantron** [comment]
Is it correct that esy does not do a recursive git clone?

For comparison, following the instructions in the README, IIRC, it's not necessary to init submodules. The instruction ask for `git clone --recursive`.

I also made sure to check this with opam `--dev-repo` pinning. This also works immediately, without the need to init submodules manually. So, I suspect (but did not verify) that opam is doing `git clone --recursive`.

If this is all correct, I think esy should also do `git clone --recursive`, unless there is some reason not to, motivated by something else in the ecosystem.

**Comment by aantron** [comment]
Sorry, `--recurse-submodules`.

**Comment by andreypopp** [comment]
That's a good point! Made an issue with esy/esy.

**Comment by aantron** [comment]
Great, subscribed to it :) And just to pile on one more case, Travis seems to do `--recurse-submodules` internally, because it ends up with the luv, gyp, and libuv sources without any special commands issued for that in this repo's Travis script.
