### ISSUE TITLE
OpenBSD build fails

### ISSUE THREAD

**Issue by mndrix** [aantron/luv#143]
OpenBSD doesn't have the constants `AI_ALL` and `AI_V4MAPPED`, so building on that platform fails. I'm happy to submit a pull request, if you can suggest how you'd like it fixed. I was able to build by removing all references to those constants, but I assume that's not what you want.

<details>
<summary>Here are the C compiler errors</summary>

```
generate_types_step_2.c:796:39: error: use of undeclared identifier 'AI_ALL'
     enum { check_AI_ALL_const = (int)AI_ALL };
                                      ^
generate_types_step_2.c:797:15: error: use of undeclared identifier 'AI_ALL'
     int v = (AI_ALL);
              ^
generate_types_step_2.c:803:44: error: use of undeclared identifier 'AI_V4MAPPED'
     enum { check_AI_V4MAPPED_const = (int)AI_V4MAPPED };
                                           ^
generate_types_step_2.c:804:15: error: use of undeclared identifier 'AI_V4MAPPED'
     int v = (AI_V4MAPPED);
              ^
4 errors generated.
```
</details>

<details>
<summary>Here is the build output</summary>

```
#=== ERROR while compiling luv.0.5.11 =========================================#
# context     2.1.4 | openbsd/x86_64 | ocaml-base-compiler.5.0.0 | https://opam.ocaml.org#28feb0dc
# path        ~/.opam/5.0.0/.opam-switch/build/luv.0.5.11
# command     ~/.opam/5.0.0/bin/dune build -p luv -j 4
# exit-code   1
# env-file    ~/.opam/log/luv-39113-378b44.env
# output-file ~/.opam/log/luv-39113-378b44.out
### output ###
# generate_types_step_2.c:804:15: error: use of undeclared identifier 'AI_V4MAPPED'
# [...]
# 4 errors generated.
# File "_build/.dune/default/src/c/dune", line 45, characters 0-813:
# 45 | (rule
# 46 |  (targets libuv.a dlluv%{ext_dll})
# 47 |  (deps (source_tree vendor))
# ....
# 62 |    "cp vendor/libuv/libuv.so.1.0.0 dlluv.so || \
# 63 |     cp vendor/libuv/libuv.1.dylib dlluv.so || \
# 64 |     cp vendor/bin/libuv-1.dll dlluv.dll")))))
# (cd _build/default/src/c && /usr/local/bin/bash -e -u -o pipefail -c 'cp vendor/libuv/libuv.
so.1.0.0 dlluv.so || cp vendor/libuv/libuv.1.dylib dlluv.so || cp vendor/bin/libuv-1.dll dlluv
.dll') &> /dev/null
# Command exited with code 1.
```
</details>

I've attached the output file [luv-39113-378b44.out](https://github.com/aantron/luv/files/10492974/log-out.txt)

**Comment by aantron** [comment]
`generate_types_start.c` includes `helpers.h` into the file it generates:

https://github.com/aantron/luv/blob/fbb87daff2b61aee747c56224b193d554345302c/src/c/generate_types_start.ml#L6-L15

It might be sufficient to just add some `#ifndef`s, guarded by a macro test for OpenBSD, to the beginning of this file, as already done for some constants on Windows:

https://github.com/aantron/luv/blob/fbb87daff2b61aee747c56224b193d554345302c/src/c/helpers.h#L22-L36

We would then probably want to just document that `AI_ALL` and `AI_V4MAPPED` are meaningless on OpenBSD.

Would you still be willing to open a PR for this? Otherwise, I am happy to fix this within a few days. Thank you!

**Comment by mndrix** [comment]
Sorry for the slow response. I've been traveling for the last couple weeks. It doesn't look like I'll be able to get to this anytime soon.  If you're willing to take it from here, that'd be great. Thanks.

**Comment by aantron** [comment]
I don't have ready access to an OpenBSD machine, unfortunately, so I can only make very slow progress.
