### ISSUE TITLE
Examples: show how to use luv with the let* syntax

### ISSUE THREAD

**Issue by aantron** [aantron/luv#16]

**Comment by andreypopp** [comment]
Maybe it's rather a thing for repromise/lwt? To add `Syntax` module there with definitions for `let*`.

**Comment by andreypopp** [comment]
I see you've created the same issues for repromise, sorry for the noise.

**Comment by aantron** [comment]
No problem :) This repo can also benefit from it, because of the pervasive CPS/callbacks. This leads to some pretty bad nesting, if taking a look at any of the straight-libuv examples:

https://github.com/aantron/luv/blob/7e8deed5093ea71c8b618d8a0ac7a5acc1658738/example/http_get/http_get.ml#L88-L92

but also offers the opportunity to rewrite the code with a `let`-syntax, since the CPS is disciplined :)

**Comment by aantron** [comment]
We can probably convert all the examples to use `let*`, because Dune supports preprocessing to emulate `let*` on older compilers. That includes Lwt, Repromise, and direct-Luv (CPS) examples.

**Comment by aantron** [comment]
...though it might be good to leave some direct-Luv in direct style, so people can understand clearly what the API actually is.
