### ISSUE TITLE
Define proper variants for enum types

### ISSUE THREAD

**Issue by aantron** [aantron/luv#22]
Most enum types are currently exposed as abstract integers in an effort to provide a more "raw" binding. However, the cost of using variants instead is trivial, and variants are much easier to use.

**Comment by andreypopp** [comment]
Does this proposal include `Luv.Error.t` as well?

**Comment by aantron** [comment]
Yes. What are your thoughts on that?

**Comment by andreypopp** [comment]
I’m all for it!

**Comment by aantron** [comment]
Done in https://github.com/aantron/luv/compare/e0788bd840219427a2744963f11fff68f2d20087...af793efb389707f68f2492644cda67399dfbc20e.

I chose polymorphic variants for all flags, except the few that I replaced with optional arguments. Generally, system flags (or abstractions of them) became polymorphic variants, and libuv-specific option flags that have few values became optional arguments.
