### ISSUE TITLE
Minimum OCaml version for using Luv?

### ISSUE THREAD

**Issue by RealyUniqueName** [aantron/luv#82]
Not an issue, but I don't know where to ask this question.

What's the minimum OCaml version required to use Luv? Can I use it with OCaml 4.06 or even 4.02?

**Comment by aantron** [comment]
Questions are fair for issues :)

Yes, you can use Luv with 4.02.

A good way to find that out is the constraints in the `opam` file of a project (in case you are using esy, esy also reads this file):

https://github.com/aantron/luv/blob/c252e1eaae1a441e8f1aeb9c9704c65d6834f4af/luv.opam#L19

In case this metadata is overly optimistic, the CI can help to double-check. Luv is tested on 4.02.3. Latest build and test results are [here](https://github.com/aantron/luv/runs/1169181097).
